In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from datetime import datetime, timedelta

In [4]:
product_data= pd.read_csv('Dataset/PRODUCT_data.csv')
product_batch_data= pd.read_csv('Dataset/PRODUCT_BATCH_data.csv')
transaction_data= pd.read_csv('Dataset/TRANSACTION_data.csv')
# transaction_product_data_1= pd.read_csv('TRANSACTION_PRODUCT_1.csv')
# transaction_product_data_2= pd.read_csv('TRANSACTION_PRODUCT_2.csv')
# transaction_data_combined= pd.read_csv('TRANSACTION_DATA_combined.csv')
# transaction_product_combined=pd.read_csv('transaction_product_combined.csv')
transaction_product_data_1a=pd.read_csv('Dataset/transaction_product_data_1a.csv')

In [3]:
transaction_data['customer_id'] = np.random.randint(1, 4000, len(transaction_data))

In [1]:
transaction_data = transaction_data[transaction_data['net_amount'] > 0]

NameError: name 'transaction_data' is not defined

In [20]:
# Add random expiry_date to product_batch_data

# Generate random expiry dates within a range
start_date = datetime.today()
end_date = start_date + timedelta(days=365)

# Add a new column for expiry_date
product_batch_data['expiry_date'] = [random.uniform(start_date, end_date) for _ in range(len(product_batch_data))]

In [ ]:
product_data.drop(columns=[col for col in product_data.columns if col not in ['id','unit_id','name','product_type_id','product_measurement_unit_id','product_manufacture_id','product_brand_id','product_rack_id','is_expiry','default_discount_percentage','max_discount_percentage','is_stock_data','is_consumable','is_nil_stock','sales_price','expiry_days']], inplace=True)

product_batch_data.drop(columns=[col for col in product_batch_data.columns if col not in ['id','unit_id','store_outlet_id','product_id','transaction_id','supplier_id','purchase_type_id','counter_id','batch_num','mrp','purchase_price','purchase_rate','sales_price','purchase_discount_percentage','sales_discount_percentage','units_per_pack','opening_stock','current_stock','expiry_date']], inplace=True)

In [7]:
# prompt: split transaction_product_combined into 6 dataset

transaction_product_data_1a = transaction_product_combined[:100000]
transaction_product_data_2a = transaction_product_combined[100000:200000]
transaction_product_data_3a = transaction_product_combined[200000:300000]
transaction_product_data_4a = transaction_product_combined[300000:400000]
transaction_product_data_5a = transaction_product_combined[400000:500000]
transaction_product_data_6a = transaction_product_combined[500000:600000]

In [10]:
transaction_product_data_1a['Store_outlet_id']=0
for i in range(100000):
    if transaction_product_data_1a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_1a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_1a['transaction_id'][i]]['store_outlet_id'].iloc[0]

transaction_product_data_2a['Store_outlet_id']=0
for i in range(100000,200000):
    if transaction_product_data_2a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_2a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_2a['transaction_id'][i]]['store_outlet_id'].iloc[0]
        
transaction_product_data_3a['Store_outlet_id']=0
for i in range(200000,300000):
    if transaction_product_data_3a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_3a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_3a['transaction_id'][i]]['store_outlet_id'].iloc[0]

transaction_product_data_5a['Store_outlet_id']=0
for i in range(400000,500000):
    if transaction_product_data_5a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_5a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_5a['transaction_id'][i]]['store_outlet_id'].iloc[0]
        
transaction_product_data_6a['Store_outlet_id']=0
for i in range(500000,600000):
    if transaction_product_data_6a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_6a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_6a['transaction_id'][i]]['store_outlet_id'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_1a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_1a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_1a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_2a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_2a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_2a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_3a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_3a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_3a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_5a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_5a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_5a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_6a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\843467997.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_6a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_6a['transaction_id'][i]]['store_outlet_id'].iloc[0]

In [21]:

transaction_product_data_1a['customer_id']=0
for i in range(100000):
    if transaction_product_data_1a['transaction_id'][i] in transaction_data['id']:
        transaction_product_data_1a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_1a['transaction_id'][i]]['customer_id'].iloc[0]
      
transaction_product_data_2a['customer_id']=0
for i in range(100000,200000):
    if transaction_product_data_2a['transaction_id'][i] in transaction_data['id']:
        transaction_product_data_2a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_2a['transaction_id'][i]]['customer_id'].iloc[0]

transaction_product_data_3a['customer_id']=0
for i in range(200000,300000):
    if transaction_product_data_3a['transaction_id'][i] in transaction_data['id']:
        transaction_product_data_3a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_3a['transaction_id'][i]]['customer_id'].iloc[0]

transaction_product_data_5a['customer_id']=0
for i in range(400000,500000):
    if transaction_product_data_5a['transaction_id'][i] in transaction_data['id']:
        transaction_product_data_5a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_5a['transaction_id'][i]]['customer_id'].iloc[0]
    
transaction_product_data_6a['customer_id']=0
for i in range(500000,600000):
    if transaction_product_data_6a['transaction_id'][i] in transaction_data['id']:
        transaction_product_data_6a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_6a['transaction_id'][i]]['customer_id'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\2159524921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_1a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\2159524921.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_1a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_1a['transaction_id'][i]]['customer_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\2159524921.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_2a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_14640\2159524921.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_2a['customer_id'][i] = transaction_data[transaction_data['id'] == transaction_product_data_2a['transaction_id'][i]]['customer_id'].iloc[0]

In [ ]:
transaction_product_data_1a['transaction_date']=0
for i in range(100000):
    if transaction_product_data_1a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_1a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_1a['transaction_id'][i]]['transaction_date'].iloc[0]

transaction_product_data_2a['transaction_date']=0
for i in range(100000,20000):
    if transaction_product_data_2a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_2a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_2a['transaction_id'][i]]['transaction_date'].iloc[0]

transaction_product_data_3a['transaction_date']=0
for i in range(100000):
    if transaction_product_data_3a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_3a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_3a['transaction_id'][i]]['transaction_date'].iloc[0]
        
transaction_product_data_5a['transaction_date']=0
for i in range(100000):
    if transaction_product_data_5a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_5a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_5a['transaction_id'][i]]['transaction_date'].iloc[0]

transaction_product_data_6a['transaction_date']=0
for i in range(100000):
    if transaction_product_data_6a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_6a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_6a['transaction_id'][i]]['transaction_date'].iloc[0]

In [5]:
transaction_product_data_7a = transaction_product_combined[600000:700000]
transaction_product_data_8a = transaction_product_combined[700000:800000]
transaction_product_data_9a = transaction_product_combined[800000:900000]
transaction_product_data_10a = transaction_product_combined[900000:1000000]
transaction_product_data_11a = transaction_product_combined[1000000:]

In [7]:
transaction_product_data_7a['Store_outlet_id']=0
for i in range(600000,700000):
    if transaction_product_data_7a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_7a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_7a['transaction_id'][i]]['store_outlet_id'].iloc[0]

transaction_product_data_8a['Store_outlet_id']=0
for i in range(700000,800000):
    if transaction_product_data_8a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_8a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_8a['transaction_id'][i]]['store_outlet_id'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\228960047.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_7a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\228960047.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_7a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_7a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\228960047.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_8a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\228960047.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_8a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_8a['transaction_id'][i]]['store_outlet_id'].iloc[0]

In [8]:
transaction_product_data_9a['Store_outlet_id']=0
for i in range(800000,900000):
    if transaction_product_data_9a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_9a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_9a['transaction_id'][i]]['store_outlet_id'].iloc[0]

transaction_product_data_10a['Store_outlet_id']=0
for i in range(900000,1000000):
    if transaction_product_data_10a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_10a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_10a['transaction_id'][i]]['store_outlet_id'].iloc[0]
        
transaction_product_data_11a['Store_outlet_id']=0
for i in range(1000000,len(transaction_data_combined)):
    if transaction_product_data_11a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_11a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_11a['transaction_id'][i]]['store_outlet_id'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3855760277.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_9a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3855760277.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_9a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_9a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3855760277.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_10a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3855760277.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_10a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_10a['transaction_id'][i]]['store_outlet_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3855760277.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_11a['Store_outlet_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3855760277.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_11a['Store_outlet_id'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_11a['transaction_id'][i]]['store_outlet_id'].iloc[0]

In [10]:
transaction_product_data_7a['customer_id']=0
for i in range(600000,700000):
    if transaction_product_data_7a['transaction_id'][i] in transaction_data['transaction_id']:
        transaction_product_data_7a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_7a['transaction_id'][i]]['customer_id'].iloc[0]

transaction_product_data_8a['customer_id']=0
for i in range(700000,800000):
    if transaction_product_data_8a['transaction_id'][i] in transaction_data['transaction_id']:
        transaction_product_data_8a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_8a['transaction_id'][i]]['customer_id'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3638898721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_7a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3638898721.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_7a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_7a['transaction_id'][i]]['customer_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3638898721.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_8a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\3638898721.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_8a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_8a['transaction_id'][i]]['customer_id'].iloc[0]

In [11]:
transaction_product_data_9a['customer_id']=0
for i in range(800000,900000):
    if transaction_product_data_9a['transaction_id'][i] in transaction_data['transaction_id']:
        transaction_product_data_9a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_9a['transaction_id'][i]]['customer_id'].iloc[0]

transaction_product_data_10a['customer_id']=0
for i in range(900000,1000000):
    if transaction_product_data_10a['transaction_id'][i] in transaction_data['transaction_id']:
        transaction_product_data_10a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_10a['transaction_id'][i]]['customer_id'].iloc[0]
        
transaction_product_data_11a['customer_id']=0
for i in range(1000000,len(transaction_data_combined)):
    if transaction_product_data_11a['transaction_id'][i] in transaction_data['transaction_id']:
        transaction_product_data_11a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_11a['transaction_id'][i]]['customer_id'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\619623575.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_9a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\619623575.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_9a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_9a['transaction_id'][i]]['customer_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\619623575.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_10a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\619623575.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_10a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_10a['transaction_id'][i]]['customer_id'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\619623575.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_11a['customer_id']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\619623575.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_11a['customer_id'][i] = transaction_data[transaction_data['transaction_id'] == transaction_product_data_11a['transaction_id'][i]]['customer_id'].iloc[0]

In [12]:
transaction_product_data_7a['transaction_date']=0
for i in range(600000,700000):
    if transaction_product_data_7a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_7a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_7a['transaction_id'][i]]['transaction_date'].iloc[0]

transaction_product_data_8a['transaction_date']=0
for i in range(700000,80000):
    if transaction_product_data_8a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_8a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_8a['transaction_id'][i]]['transaction_date'].iloc[0]

transaction_product_data_9a['transaction_date']=0
for i in range(800000,900000):
    if transaction_product_data_9a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_9a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_9a['transaction_id'][i]]['transaction_date'].iloc[0]
        
transaction_product_data_10a['transaction_date']=0
for i in range(900000,1000000):
    if transaction_product_data_10a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_10a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_10a['transaction_id'][i]]['transaction_date'].iloc[0]

transaction_product_data_11a['transaction_date']=0
for i in range(1000000,len(transaction_data_combined)):
    if transaction_product_data_11a['transaction_id'][i] in transaction_data_combined['id']:
        transaction_product_data_11a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_11a['transaction_id'][i]]['transaction_date'].iloc[0]

C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_7a['transaction_date']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_7a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_7a['transaction_id'][i]]['transaction_date'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_8a['transaction_date']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_9a['transaction_date']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_9a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_9a['transaction_id'][i]]['transaction_date'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_10a['transaction_date']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_10a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_10a['transaction_id'][i]]['transaction_date'].iloc[0]
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_11a['transaction_date']=0
C:\Users\bhara\AppData\Local\Temp\ipykernel_7872\967761652.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction_product_data_11a['transaction_date'][i] = transaction_data_combined[transaction_data_combined['id'] == transaction_product_data_11a['transaction_id'][i]]['transaction_date'].iloc[0]

In [13]:
transaction_product_data_7a.to_csv('transaction_product_data_7a.csv', index=False)
transaction_product_data_8a.to_csv('transaction_product_data_8a.csv', index=False)
transaction_product_data_9a.to_csv('transaction_product_data_9a.csv', index=False)
transaction_product_data_10a.to_csv('transaction_product_data_10a.csv', index=False)
transaction_product_data_11a.to_csv('transaction_product_data_11a.csv', index=False)

In [3]:
transaction_product_combined_1a_11a = pd.concat([transaction_product_data_1a, transaction_product_data_2a,transaction_product_data_3a,transaction_product_data_5a,transaction_product_data_6a,transaction_product_data_7a,transaction_product_data_8a,transaction_product_data_9a,transaction_product_data_10a,transaction_product_data_11a], ignore_index=True)
transaction_product_combined_1a_11a.to_csv('transaction_product_combined_1a_11a.csv', index=False)

In [ ]:
transaction_product_data_1a.to_csv('transaction_product_data_1a.csv', index=False)
transaction_product_data_2a.to_csv('transaction_product_data_2a.csv', index=False)
transaction_product_data_3a.to_csv('transaction_product_data_3a.csv', index=False)
transaction_product_data_5a.to_csv('transaction_product_data_5a.csv', index=False)
transaction_product_data_6a.to_csv('transaction_product_data_6a.csv', index=False)
transaction_data.to_csv('transaction_data.csv', index=False)

In [9]:
transaction_product_combined_1a_6a = pd.concat([transaction_product_data_1a, transaction_product_data_2a,transaction_product_data_3a,transaction_product_data_5a,transaction_product_data_6a], ignore_index=True)
transaction_product_combined_1a_6a.to_csv('transaction_product_combined_1a_6a.csv', index=False)

NameError: name 'transaction_product_data_1a' is not defined

In [10]:
# prompt: drop rows with qty=0

transaction_product_combined = transaction_product_combined[transaction_product_combined["qty"] > 10]

In [11]:
#  sort product_batch_data in desending order of sales price

product_batch_data.sort_values(by="sales_price", ascending=False, inplace=True)

In [12]:
product_batch_data=product_batch_data[product_batch_data['sales_price'] <= 2.250000e+05	]

In [13]:
product_batch_data['profit']=0
profit=0
for i in range(85526):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit

C:\Users\bhara\AppData\Local\Temp\ipykernel_17432\385711544.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

In [17]:
product_batch_data['profit']=0
profit=0
for i in range(85528,200000):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit

C:\Users\bhara\AppData\Local\Temp\ipykernel_17432\535438325.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

In [18]:
product_batch_data['profit']=0
profit=0
c=0
for i in range(200000,300000):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
            c+=1
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit
print(c)

C:\Users\bhara\AppData\Local\Temp\ipykernel_17432\908358325.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

In [24]:
product_batch_data['profit']=0
profit=0
for i in range(300000,324713):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit

C:\Users\bhara\AppData\Local\Temp\ipykernel_17432\3246620111.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

In [3]:
product_batch_data['profit']=0
profit=0
c=0
for i in range(324714,400000):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
            c+=1
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit
print(c)

C:\Users\bhara\AppData\Local\Temp\ipykernel_12736\2395900219.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

0

In [10]:
profit=0
c=0
for i in range(500000,550000):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
            c+=1
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit
print(c)

C:\Users\bhara\AppData\Local\Temp\ipykernel_18984\608072623.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

0

In [13]:
product_batch_data.to_csv('product_batch_data.csv', index=False)

In [12]:
profit=0
c=0
for i in range(550000,600000):
    if product_batch_data['id'][i] in list(transaction_product_combined['product_batch_id']):
        qty_sum=transaction_product_combined[transaction_product_combined['product_batch_id']==product_batch_data['id'][i]]['qty'].sum()
        if product_batch_data['sales_price'][i]==0:
            profit=0
            c+=1
        else:
            profit=(product_batch_data['sales_price'][i]-product_batch_data['purchase_rate'][i])*qty_sum
    product_batch_data['profit'][i]=profit
print(c)

C:\Users\bhara\AppData\Local\Temp\ipykernel_18984\46006012.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_batch_data['profit'][i]=profit

0

In [14]:
product_batch_data.head()

,id,unit_id,store_outlet_id,product_id,transaction_id,supplier_id,purchase_type_id,counter_id,batch_num,mrp,purchase_price,purchase_rate,sales_price,purchase_discount_percentage,sales_discount_percentage,units_per_pack,opening_stock,current_stock,expiry_date,profit
0,441291,18,14,152158,718364.0,21995.0,11,21,1390,250000.0,158629.38,158629.38,225000.0,0.0,10.0,1,0.0,0.0,NaN,0.0
1,441292,18,18,152158,733660.0,21995.0,11,21,1390,250000.0,158629.38,158629.38,225000.0,0.0,10.0,1,0.0,0.0,NaN,0.0
2,411712,69,91,135679,NaN,21874.0,61,80,2020,177800.0,17775.04,17775.04,172360.0,0.0,0.0,1,235.0,235.0,NaN,0.0
3,411716,69,91,135679,NaN,21874.0,61,80,2080,170360.0,17775.04,17775.04,170360.0,0.0,0.0,1,10.0,10.0,NaN,0.0
4,433619,18,18,150281,733656.0,21995.0,11,21,1030,147000.0,96738.02,96738.02,132300.0,0.0,10.0,1,0.0,0.0,NaN,0.0

In [15]:
len(product_batch_data[product_batch_data['profit']!=0])

198841

In [16]:
product_batch_data['profit'].unique()

array([  0.     , 876.     , 169.38   , ...,  50.61186, 440.22   ,
       163.242  ])

In [17]:
len(product_batch_data)

1064490

In [23]:
product_batch_data['id'][324715]

4770

In [21]:
product_batch_data= pd.read_csv('PRODUCT_BATCH_data.csv')
transaction_product_combined=pd.read_csv('transaction_product_combined.csv')

In [2]:
product_batch_data= pd.read_csv('PRODUCT_BATCH_data.csv')
transaction_product_data_1a=pd.read_csv('transaction_product_data_1a.csv')

In [12]:
product_data= pd.read_csv('PRODUCT.csv')

In [3]:
# Calculate profit for each transaction
transaction_product_data_1a['profit'] = (transaction_product_data_1a['sales_price'] - transaction_product_data_1a['rate']) * transaction_product_data_1a['qty']

In [5]:
transaction_product_data_1a.head()

,index,id,transaction_id,product_id,product_batch_id,qty,rate,mrp_rate,sales_price,cgst_amount,sgst_amount,amount,total_amount,cost,Store_outlet_id,customer_id,transaction_date,profit
0,0,2600234,749599,43796,413609,30.0,28.00,39.0,28.00,0.00,0.00,840.00,840.00,25.0,46,983,2021-12-08,0.00
1,2,2600236,749600,63767,243213,1.2,45.00,45.0,45.00,0.00,0.00,54.00,54.00,0.0,90,678,2021-12-08,0.00
2,3,2600237,749600,63915,216407,2.0,23.93,30.0,28.24,4.31,4.31,47.86,56.48,0.0,90,678,2021-12-08,8.62
3,10,2600244,749600,64308,343703,2.0,45.00,45.0,45.00,0.00,0.00,90.00,90.00,0.0,90,678,2021-12-08,0.00
4,12,2600246,749600,64644,322825,6.7,24.00,24.0,24.00,0.00,0.00,160.80,160.80,0.0,90,678,2021-12-08,0.00

In [22]:
# prompt: top 5 most profitable products by store


# # Read the transaction data
# transaction_data = pd.read_csv('transaction_data.csv')

# # Read the product data
# product_data = pd.read_csv('product_data.csv')

# Merge the transaction and product data
merged_data = pd.merge(transaction_product_data_1a, product_batch_data, on='product_id')

# Calculate the profit for each product in each store
product_profit = merged_data.groupby(['Store_outlet_id', 'product_id'])['profit_y'].sum()

# Get the top 5 most profitable products for each store
top_5_products_by_store = product_profit.groupby('Store_outlet_id').nlargest(5)

# Print the top 5 most profitable products for each store
print("Top 5 Most Profitable Products by Store:")
for store_id, products in top_5_products_by_store.groupby('Store_outlet_id'):
    print(f"\nStore ID: {store_id}")
    for product_id, profit in products.items():
        # product_name = product_data[product_data['id'] == product_id]['name'].values[0]
        print(f"- Product Id: {product_id[2]}, Profit: {profit:.2f}")

Top 5 Most Profitable Products by Store:

Store ID: 2
- Product Id: 269, Profit: 5169731.09
- Product Id: 137, Profit: 1124412.03
- Product Id: 60, Profit: 1105029.94
- Product Id: 19630, Profit: 933677.22
- Product Id: 19635, Profit: 716402.10

Store ID: 4
- Product Id: 3479, Profit: 574242.60
- Product Id: 925, Profit: 466189.62
- Product Id: 2934, Profit: 405242.18
- Product Id: 2057, Profit: 352001.40
- Product Id: 25041, Profit: 133072.50

Store ID: 6
- Product Id: 6693, Profit: 72007.39
- Product Id: 56008, Profit: 2430.00
- Product Id: 7314, Profit: 0.00

Store ID: 9
- Product Id: 8513, Profit: 0.00

Store ID: 11
- Product Id: 154214, Profit: 69909.04
- Product Id: 1775, Profit: 56564.80
- Product Id: 3135, Profit: 34723.51
- Product Id: 2089, Profit: 27453.79
- Product Id: 2862, Profit: 26996.42

Store ID: 13
- Product Id: 3843, Profit: 65953445.92
- Product Id: 3798, Profit: 8523921.88
- Product Id: 3797, Profit: 8453924.90
- Product Id: 4139, Profit: 7502069.13
- Product Id: 3808, Profit: 5299686.00

Store ID: 18
- Product Id: 107712, Profit: 44676.60
- Product Id: 107499, Profit: 40952.88
- Product Id: 107500, Profit: 27567.24
- Product Id: 107709, Profit: 26180.64
- Product Id: 136856, Profit: 24378.00

Store ID: 22
- Product Id: 99940, Profit: 32500412.24
- Product Id: 101318, Profit: 30114784.56
- Product Id: 101362, Profit: 21316136.00
- Product Id: 101300, Profit: 14847563.29
- Product Id: 69437, Profit: 10947760.46

Store ID: 23
- Product Id: 19648, Profit: 17516066.76
- Product Id: 19649, Profit: 13550463.73
- Product Id: 19627, Profit: 5827157.86
- Product Id: 9439, Profit: 2855691.80
- Product Id: 9403, Profit: 1645962.48

Store ID: 25
- Product Id: 21033, Profit: 38789697.77
- Product Id: 23067, Profit: 37209879.68
- Product Id: 21022, Profit: 15681855.58
- Product Id: 20884, Profit: 5778089.28
- Product Id: 57137, Profit: 2292233.53

Store ID: 32
- Product Id: 33831, Profit: 22218.00
- Product Id: 33836, Profit: 7343.85
- Product Id: 33833, Profit: 6428.12
- Product Id: 33967, Profit: 742.32
- Product Id: 33822, Profit: 0.00

Store ID: 33
- Product Id: 42750, Profit: 0.00
- Product Id: 42754, Profit: 0.00
- Product Id: 42759, Profit: 0.00
- Product Id: 44824, Profit: 0.00
- Product Id: 99944, Profit: 0.00

Store ID: 35
- Product Id: 23598, Profit: 1266836.96
- Product Id: 23599, Profit: 410312.00
- Product Id: 24781, Profit: 409154.20
- Product Id: 35409, Profit: 86656.64
- Product Id: 23698, Profit: 55307.10

Store ID: 37
- Product Id: 39170, Profit: 213701.18
- Product Id: 39838, Profit: 184287.04
- Product Id: 38783, Profit: 129311.58
- Product Id: 38578, Profit: 124790.25
- Product Id: 50770, Profit: 116262.36

Store ID: 45
- Product Id: 153218, Profit: 2720577.90
- Product Id: 60197, Profit: 1481326.08
- Product Id: 57840, Profit: 1380182.76
- Product Id: 153206, Profit: 841196.65
- Product Id: 57586, Profit: 435488.64

Store ID: 46
- Product Id: 33638, Profit: 58119454.02
- Product Id: 33642, Profit: 46786663.34
- Product Id: 33650, Profit: 41625048.37
- Product Id: 33651, Profit: 20242440.96
- Product Id: 33117, Profit: 17732397.53

Store ID: 49
- Product Id: 31148, Profit: 2054016.29
- Product Id: 30904, Profit: 551877.96
- Product Id: 68114, Profit: 324303.39
- Product Id: 38183, Profit: 307492.30
- Product Id: 26557, Profit: 297498.87

Store ID: 51
- Product Id: 52372, Profit: 139958.00
- Product Id: 53565, Profit: 60142.08
- Product Id: 53674, Profit: 47975.10
- Product Id: 53781, Profit: 36301.48
- Product Id: 52383, Profit: 17516.60

Store ID: 53
- Product Id: 34619, Profit: 3122917.71
- Product Id: 34553, Profit: 2249752.80
- Product Id: 34450, Profit: 613407.72
- Product Id: 34497, Profit: 474723.75
- Product Id: 34422, Profit: 470147.64

Store ID: 61
- Product Id: 43152, Profit: 0.00
- Product Id: 43158, Profit: 0.00
- Product Id: 102086, Profit: 0.00

Store ID: 62
- Product Id: 41921, Profit: 581990.55
- Product Id: 41950, Profit: 94309.92
- Product Id: 41875, Profit: 81376.82
- Product Id: 42367, Profit: 69070.92
- Product Id: 42081, Profit: 66510.42

Store ID: 63
- Product Id: 44454, Profit: 0.00

Store ID: 64
- Product Id: 43920, Profit: 566269.49
- Product Id: 43843, Profit: 153703.22
- Product Id: 43938, Profit: 32585.50
- Product Id: 44280, Profit: 15758.70
- Product Id: 43833, Profit: 12597.00

Store ID: 65
- Product Id: 38072, Profit: 140292.66
- Product Id: 38057, Profit: 120758.96
- Product Id: 50069, Profit: 84483.90
- Product Id: 38071, Profit: 28435.56
- Product Id: 49345, Profit: 3540.00

Store ID: 66
- Product Id: 36347, Profit: 0.00
- Product Id: 36348, Profit: 0.00
- Product Id: 36349, Profit: 0.00
- Product Id: 36351, Profit: 0.00
- Product Id: 36352, Profit: 0.00

Store ID: 68
- Product Id: 36887, Profit: 893396.49
- Product Id: 36930, Profit: 247400.16
- Product Id: 36629, Profit: 76854.00
- Product Id: 36860, Profit: 58797.80
- Product Id: 36685, Profit: 25892.50

Store ID: 70
- Product Id: 37726, Profit: 6310280.00
- Product Id: 64983, Profit: 1005111.38
- Product Id: 47073, Profit: 561385.00
- Product Id: 105890, Profit: 522850.64
- Product Id: 105887, Profit: 467355.00

Store ID: 73
- Product Id: 48118, Profit: 35513916.00
- Product Id: 48343, Profit: 14903786.24
- Product Id: 54012, Profit: 11314962.12
- Product Id: 48131, Profit: 10908249.92
- Product Id: 48351, Profit: 9785560.00

Store ID: 77
- Product Id: 46346, Profit: 30465.50
- Product Id: 45907, Profit: 17107.43
- Product Id: 45937, Profit: 14766.77
- Product Id: 46361, Profit: 9650.68
- Product Id: 45914, Profit: 9366.83

Store ID: 79
- Product Id: 44864, Profit: 0.00
- Product Id: 44865, Profit: 0.00
- Product Id: 44866, Profit: 0.00
- Product Id: 44872, Profit: 0.00
- Product Id: 44880, Profit: 0.00

Store ID: 82
- Product Id: 57073, Profit: 45354851.10
- Product Id: 56815, Profit: 14179823.10
- Product Id: 56819, Profit: 5080146.49
- Product Id: 56731, Profit: 888595.47
- Product Id: 113731, Profit: 742376.66

Store ID: 87
- Product Id: 62961, Profit: 12136395.07
- Product Id: 62964, Profit: 321405.67
- Product Id: 62972, Profit: 244483.30
- Product Id: 62963, Profit: 131389.28
- Product Id: 62960, Profit: 45476.82

Store ID: 88
- Product Id: 100009, Profit: 24164382.75
- Product Id: 104532, Profit: 3802998.76
- Product Id: 99998, Profit: 3601690.47
- Product Id: 100108, Profit: 2157558.39
- Product Id: 99997, Profit: 2143640.38

Store ID: 89
- Product Id: 103300, Profit: 268537.90
- Product Id: 103147, Profit: 59051.10
- Product Id: 103310, Profit: 16357.60
- Product Id: 103128, Profit: 14649.12
- Product Id: 103112, Profit: 0.00

Store ID: 90
- Product Id: 64013, Profit: 2996203.04
- Product Id: 63756, Profit: 1357320.04
- Product Id: 63767, Profit: 1296440.13
- Product Id: 63768, Profit: 670889.66
- Product Id: 63794, Profit: 321770.62

Store ID: 92
- Product Id: 153177, Profit: 773275.44
- Product Id: 135912, Profit: 300072.20
- Product Id: 135905, Profit: 170388.00
- Product Id: 157374, Profit: 41068.11
- Product Id: 135868, Profit: 18545.26

Store ID: 94
- Product Id: 113131, Profit: 0.00
- Product Id: 113132, Profit: 0.00
- Product Id: 113133, Profit: 0.00
- Product Id: 113274, Profit: 0.00
- Product Id: 113278, Profit: 0.00

Store ID: 96
- Product Id: 105461, Profit: 0.00
- Product Id: 105463, Profit: 0.00
- Product Id: 105464, Profit: 0.00
- Product Id: 105465, Profit: 0.00
- Product Id: 105470, Profit: 0.00

Store ID: 98
- Product Id: 111914, Profit: 0.00
- Product Id: 111916, Profit: 0.00
- Product Id: 112020, Profit: 0.00
- Product Id: 112071, Profit: 0.00
- Product Id: 112113, Profit: 0.00

Store ID: 101
- Product Id: 67706, Profit: 849715.26
- Product Id: 149252, Profit: 277636.00
- Product Id: 155994, Profit: 145948.32
- Product Id: 69398, Profit: 102009.96
- Product Id: 80625, Profit: 87143.02

Store ID: 104
- Product Id: 111167, Profit: 1342735.11
- Product Id: 111111, Profit: 1304696.77
- Product Id: 111243, Profit: 1245818.53
- Product Id: 82268, Profit: 730872.78
- Product Id: 111119, Profit: 692109.10

Store ID: 105
- Product Id: 82375, Profit: 564066.00
- Product Id: 82267, Profit: 337342.08
- Product Id: 82377, Profit: 76248.00
- Product Id: 82402, Profit: 29348.00
- Product Id: 82416, Profit: 17711.36

Store ID: 118
- Product Id: 136091, Profit: 275690.00
- Product Id: 136090, Profit: 245780.90
- Product Id: 136105, Profit: 226662.24
- Product Id: 155236, Profit: 103290.42
- Product Id: 124625, Profit: 102504.00

Store ID: 120
- Product Id: 125828, Profit: 1684235.07
- Product Id: 132125, Profit: 1623200.88
- Product Id: 132136, Profit: 1600878.01
- Product Id: 132160, Profit: 1362046.79
- Product Id: 125833, Profit: 787983.42

Store ID: 124
- Product Id: 140077, Profit: 54703.20
- Product Id: 147607, Profit: 18257.52
- Product Id: 147599, Profit: 18071.12
- Product Id: 151782, Profit: 7921.40
- Product Id: 146771, Profit: 6799.82

Store ID: 128
- Product Id: 154263, Profit: 443352.00
- Product Id: 154262, Profit: 179442.00
- Product Id: 154500, Profit: 100825.34
- Product Id: 155418, Profit: 69768.00
- Product Id: 153662, Profit: 54950.40

Store ID: 130
- Product Id: 160245, Profit: 2173.38
- Product Id: 160210, Profit: 1428.60
- Product Id: 160203, Profit: 525.60
- Product Id: 160255, Profit: 479.88
- Product Id: 160139, Profit: 291.70

In [7]:
merged_data.head()

,index,id_x,transaction_id_x,product_id,product_batch_id,qty,rate,mrp_rate,sales_price_x,cgst_amount,...,purchase_price,purchase_rate,sales_price_y,purchase_discount_percentage,sales_discount_percentage,units_per_pack,opening_stock,current_stock,expiry_date,profit_y
0,0,2600234,749599,43796,413609,30.0,28.0,39.0,28.0,0.0,...,28.0,28.0,35.0,0.0,18.60,1,2.0,0.0,NaN,0.0
1,0,2600234,749599,43796,413609,30.0,28.0,39.0,28.0,0.0,...,28.0,28.0,35.0,0.0,16.67,1,20.0,12.0,NaN,0.0
2,0,2600234,749599,43796,413609,30.0,28.0,39.0,28.0,0.0,...,28.0,28.0,35.0,0.0,16.67,1,0.0,0.0,NaN,0.0
3,0,2600234,749599,43796,413609,30.0,28.0,39.0,28.0,0.0,...,28.0,28.0,35.0,0.0,18.60,1,0.0,19.0,NaN,0.0
4,0,2600234,749599,43796,413609,30.0,28.0,39.0,28.0,0.0,...,27.0,27.0,35.0,0.0,16.67,1,0.0,0.0,NaN,0.0